# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZwVn023bj09jMq8mU6yZZlLk4l8Yqqzc
"""

import pandas as pd
Asilbek={
    "Fish":[ "Aliyev Abdulvosid","Abdullayev Shaxriyor","Mamadaliyev Muhammadali","Mamasoliyev Asilbek","Topvoldiyev Abbos","Soliyev Sardor","Ganiyev Abdulvosid","Soliyev Diyorbek","Asqarov diyorbek","Aliyev Ali"  ],
    "Yoshi":[  "11","16","12","14","8","17","13","9","18","15" ],
    "Maktabi":[ "6-Maktab","34-maktab","17-maktab","1-maktab","5-maktab","28-maktab","16-maktab","23-maktab","19-maktab","33-maktab" ],
    "Jinsi":[  "Erkak","Erkak","Erkak","Erkak","Erkak","Erkak","Erkak","Erkak","Erkak","Erkak"  ],
    "Manzili":[ "Fargona shahar","Andijon shaxar","Fargona viloyati","Toshkent shaxar","Toshkent viloyati","Samarqand Shaxar","Qarshi shaxar","Nukus shaxar","Guliston shaxar","Namangan shaxar"  ],

}
malumot=pd.DataFrame(Asilbek)
print(malumot)

filtr=malumot[malumot['Jinsi']=='Erkak']
print(filtr)

